### ISSUE TITLE
[wontfix] Dolphin nand won't submit scores to leaderboard

### ISSUE THREAD

**Issue by naeaemo** [dancepartyonline/gameserver#18]
Even if I dance a song, my online level don't level up even if I dance a song in the wdf (in every jd). And even if I surpass the score of someone in the global score, my score don't appear in there.(2015 - 2018)

**Comment by naeaemo** [comment]
> For the online level, you need other people in your party to level up. What do you mean by "global score"?

***Global weekly, I wasn't remembering the name, sorry-

**Comment by TermOfficial** [comment]
Are you playing on the World Dance Floor and score won't submit? It might be something out of our control.

**Comment by naeaemo** [comment]
> Are you playing on the World Dance Floor and score won't submit? It might be something out of our control.

the part of wdf not save my score happens to me in 2014, buti am saying that when i play a song, even if my score is higher than someone else's, it doesn't update
![Screenshot_1](https://github.com/dancepartyonline/gameserver/assets/156815907/cbebeb56-d772-46af-9e89-86d0edd4641e)
![Screenshot_2](https://github.com/dancepartyonline/gameserver/assets/156815907/420be341-3060-46cd-9f7a-3bc3656fa2ac)

**Comment by TermOfficial** [comment]
Are you playing on the default dolphin nand? Or is this a real console/nand?

**Comment by naeaemo** [comment]
> Are you playing on the default dolphin nand? Or is this a real console/nand?

dolphin

**Comment by TermOfficial** [comment]
that could probably be a reason why

**Comment by TermOfficial** [comment]
Yeah actually iirc you need a real nand to save scores, dolphin nand scores were disabled awhile ago

**Comment by naeaemo** [comment]
> Yeah actually iirc you need a real nand to save scores, dolphin nand scores were disabled awhile ago. If it still doesn't work with a real nand, I'll look into it

alr then, thx for answer my questions <3
